name: NAFNet-width16
model_type: ImageRestorationModel
manual_seed: 42

datasets:
  # this params is same as the keywords args taken by dataset class to instatiate
  dataset_dir: Dataset
  target_size: [256,256,3]
  batch_size: 16
  input_folder_name: blur
  target_folder_name: sharp
  validation_split: 0.1
  augmenting_list: ["random_crop", "flip_left_right", "flip_up_down", "random_contrast", "random_saturation"]
  augment_target_images: True

model:
  name: NAFNet
  model_params:
    # this model configuration is same as all the keywords args a model class takes
    # to instatiate
    width: 16
    num_enc_blocks: [1, 1, 1, 14]
    num_middle_blocks: 1
    num_dec_blocks: [1, 1, 1, 1]
    train_size: [256, 256, 3]
    dropout_rate: 0.0
    local_agg: False
    tlc_factor: 1.5

# training settings
train:
  optim_g:
    type: AdamW
    lr:  !!float 1e-3
    weight_decay: !!float  1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min:
